--------------------------------------------------------
--  File created - воскресенье-но€бр€-01-2015   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Sequence ID_SEQUENCE
--------------------------------------------------------

   CREATE SEQUENCE  "ROOT"."ID_SEQUENCE"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 100 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Table AUTOR
--------------------------------------------------------

  CREATE TABLE "ROOT"."AUTOR" 
   (	"AUTOR_ID" NUMBER(20,0), 
	"AUTOR_NAME" NVARCHAR2(30), 
	"EXPIRED" TIMESTAMP (6)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table COMMENTS
--------------------------------------------------------

  CREATE TABLE "ROOT"."COMMENTS" 
   (	"COMMENT_ID" NUMBER(20,0), 
	"NEWS_ID" NUMBER(20,0), 
	"COMMENT_TEXT" NVARCHAR2(100), 
	"CREATION_DATE" TIMESTAMP (6)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table NEWS
--------------------------------------------------------

  CREATE TABLE "ROOT"."NEWS" 
   (	"NEWS_ID" NUMBER(20,0), 
	"TITLE" NVARCHAR2(30), 
	"SHORT_TEXT" NVARCHAR2(100), 
	"FULL_TEXT" NVARCHAR2(2000), 
	"CREATION_DATE" TIMESTAMP (6), 
	"MODIFICATION_DATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table NEWS_AUTOR
--------------------------------------------------------

  CREATE TABLE "ROOT"."NEWS_AUTOR" 
   (	"NEWS_ID" NUMBER(20,0), 
	"AUTOR_ID" NUMBER(20,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table NEWS_TAG
--------------------------------------------------------

  CREATE TABLE "ROOT"."NEWS_TAG" 
   (	"NEWS_ID" NUMBER(20,0), 
	"TAG_ID" NUMBER(20,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table ROLES
--------------------------------------------------------

  CREATE TABLE "ROOT"."ROLES" 
   (	"USER_ID" NUMBER(20,0), 
	"ROLE_NAME" NVARCHAR2(50)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table TAG
--------------------------------------------------------

  CREATE TABLE "ROOT"."TAG" 
   (	"TAG_ID" NUMBER(20,0), 
	"TAG_NAME" NVARCHAR2(30)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table USER
--------------------------------------------------------

  CREATE TABLE "ROOT"."USER" 
   (	"USER_ID" NUMBER(20,0), 
	"USER_NAME" NVARCHAR2(50), 
	"LOGIN" VARCHAR2(30 BYTE), 
	"PASSWORD" VARCHAR2(30 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into ROOT.AUTOR
SET DEFINE OFF;
REM INSERTING into ROOT.COMMENTS
SET DEFINE OFF;
REM INSERTING into ROOT.NEWS
SET DEFINE OFF;
REM INSERTING into ROOT.NEWS_AUTOR
SET DEFINE OFF;
REM INSERTING into ROOT.NEWS_TAG
SET DEFINE OFF;
REM INSERTING into ROOT.ROLES
SET DEFINE OFF;
REM INSERTING into ROOT.TAG
SET DEFINE OFF;
REM INSERTING into ROOT."USER"
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index COMMENTS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ROOT"."COMMENTS_PK" ON "ROOT"."COMMENTS" ("COMMENT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index TAG_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ROOT"."TAG_PK" ON "ROOT"."TAG" ("TAG_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index AUTOR_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ROOT"."AUTOR_PK" ON "ROOT"."AUTOR" ("AUTOR_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index NEWS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ROOT"."NEWS_PK" ON "ROOT"."NEWS" ("NEWS_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_USER
--------------------------------------------------------

  CREATE UNIQUE INDEX "ROOT"."PK_USER" ON "ROOT"."USER" ("USER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table NEWS_AUTOR
--------------------------------------------------------

  ALTER TABLE "ROOT"."NEWS_AUTOR" MODIFY ("AUTOR_ID" NOT NULL ENABLE);
  ALTER TABLE "ROOT"."NEWS_AUTOR" MODIFY ("NEWS_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ROLES
--------------------------------------------------------

  ALTER TABLE "ROOT"."ROLES" MODIFY ("ROLE_NAME" NOT NULL ENABLE);
  ALTER TABLE "ROOT"."ROLES" MODIFY ("USER_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table AUTOR
--------------------------------------------------------

  ALTER TABLE "ROOT"."AUTOR" ADD CONSTRAINT "AUTOR_PK" PRIMARY KEY ("AUTOR_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "ROOT"."AUTOR" MODIFY ("EXPIRED" NOT NULL ENABLE);
  ALTER TABLE "ROOT"."AUTOR" MODIFY ("AUTOR_NAME" NOT NULL ENABLE);
  ALTER TABLE "ROOT"."AUTOR" MODIFY ("AUTOR_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table USER
--------------------------------------------------------

  ALTER TABLE "ROOT"."USER" ADD CONSTRAINT "PK_USER" PRIMARY KEY ("USER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "ROOT"."USER" MODIFY ("PASSWORD" NOT NULL ENABLE);
  ALTER TABLE "ROOT"."USER" MODIFY ("LOGIN" NOT NULL ENABLE);
  ALTER TABLE "ROOT"."USER" MODIFY ("USER_NAME" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table COMMENTS
--------------------------------------------------------

  ALTER TABLE "ROOT"."COMMENTS" ADD CONSTRAINT "COMMENTS_PK" PRIMARY KEY ("COMMENT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "ROOT"."COMMENTS" MODIFY ("CREATION_DATE" NOT NULL ENABLE);
  ALTER TABLE "ROOT"."COMMENTS" MODIFY ("COMMENT_TEXT" NOT NULL ENABLE);
  ALTER TABLE "ROOT"."COMMENTS" MODIFY ("NEWS_ID" NOT NULL ENABLE);
  ALTER TABLE "ROOT"."COMMENTS" MODIFY ("COMMENT_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TAG
--------------------------------------------------------

  ALTER TABLE "ROOT"."TAG" ADD CONSTRAINT "TAG_PK" PRIMARY KEY ("TAG_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "ROOT"."TAG" MODIFY ("TAG_NAME" NOT NULL ENABLE);
  ALTER TABLE "ROOT"."TAG" MODIFY ("TAG_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table NEWS
--------------------------------------------------------

  ALTER TABLE "ROOT"."NEWS" ADD CONSTRAINT "NEWS_PK" PRIMARY KEY ("NEWS_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "ROOT"."NEWS" MODIFY ("MODIFICATION_DATE" NOT NULL ENABLE);
  ALTER TABLE "ROOT"."NEWS" MODIFY ("CREATION_DATE" NOT NULL ENABLE);
  ALTER TABLE "ROOT"."NEWS" MODIFY ("FULL_TEXT" NOT NULL ENABLE);
  ALTER TABLE "ROOT"."NEWS" MODIFY ("SHORT_TEXT" NOT NULL ENABLE);
  ALTER TABLE "ROOT"."NEWS" MODIFY ("TITLE" NOT NULL ENABLE);
  ALTER TABLE "ROOT"."NEWS" MODIFY ("NEWS_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table NEWS_TAG
--------------------------------------------------------

  ALTER TABLE "ROOT"."NEWS_TAG" MODIFY ("TAG_ID" NOT NULL ENABLE);
  ALTER TABLE "ROOT"."NEWS_TAG" MODIFY ("NEWS_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table COMMENTS
--------------------------------------------------------

  ALTER TABLE "ROOT"."COMMENTS" ADD CONSTRAINT "FK_COMMENTS_NEWS_NEWS_ID" FOREIGN KEY ("NEWS_ID")
	  REFERENCES "ROOT"."NEWS" ("NEWS_ID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table NEWS_AUTOR
--------------------------------------------------------

  ALTER TABLE "ROOT"."NEWS_AUTOR" ADD CONSTRAINT "FK_NEWS_AUTOR_AUTOR_AUTOR_ID" FOREIGN KEY ("AUTOR_ID")
	  REFERENCES "ROOT"."AUTOR" ("AUTOR_ID") ENABLE;
  ALTER TABLE "ROOT"."NEWS_AUTOR" ADD CONSTRAINT "FK_NEWS_AUTOR_NEWS_NEWS_ID" FOREIGN KEY ("NEWS_ID")
	  REFERENCES "ROOT"."NEWS" ("NEWS_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table NEWS_TAG
--------------------------------------------------------

  ALTER TABLE "ROOT"."NEWS_TAG" ADD CONSTRAINT "FK_NEWS_TAG_NEWS_NEWS_ID" FOREIGN KEY ("NEWS_ID")
	  REFERENCES "ROOT"."NEWS" ("NEWS_ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "ROOT"."NEWS_TAG" ADD CONSTRAINT "FK_NEWS_TAG_TAG_TAG_ID" FOREIGN KEY ("TAG_ID")
	  REFERENCES "ROOT"."TAG" ("TAG_ID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ROLES
--------------------------------------------------------

  ALTER TABLE "ROOT"."ROLES" ADD CONSTRAINT "FK_ROLES_USER_USER_ID" FOREIGN KEY ("USER_ID")
	  REFERENCES "ROOT"."USER" ("USER_ID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  DDL for Trigger ID_AUTOR_TRIGGER
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "ROOT"."ID_AUTOR_TRIGGER" 
   before insert on "ROOT"."AUTOR" 
   for each row 
begin  
   if inserting then 
      if :NEW."AUTOR_ID" is null then 
         select ID_SEQUENCE.nextval into :NEW."AUTOR_ID" from dual; 
      end if; 
   end if; 
end;

/
ALTER TRIGGER "ROOT"."ID_AUTOR_TRIGGER" ENABLE;
--------------------------------------------------------
--  DDL for Trigger ID_COMMENTS_TRIGGER
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "ROOT"."ID_COMMENTS_TRIGGER" 
   before insert on "ROOT"."COMMENTS" 
   for each row 
begin  
   if inserting then 
      if :NEW."COMMENT_ID" is null then 
         select ID_SEQUENCE.nextval into :NEW."COMMENT_ID" from dual; 
      end if; 
   end if; 
end;

/
ALTER TRIGGER "ROOT"."ID_COMMENTS_TRIGGER" ENABLE;
--------------------------------------------------------
--  DDL for Trigger ID_NEWS_TRIGGER
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "ROOT"."ID_NEWS_TRIGGER" 
   before insert on "ROOT"."NEWS" 
   for each row 
begin  
   if inserting then 
      if :NEW."NEWS_ID" is null then 
         select ID_SEQUENCE.nextval into :NEW."NEWS_ID" from dual; 
      end if; 
   end if; 
end;

/
ALTER TRIGGER "ROOT"."ID_NEWS_TRIGGER" ENABLE;
--------------------------------------------------------
--  DDL for Trigger ID_TAG_TRIGGER
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "ROOT"."ID_TAG_TRIGGER" 
   before insert on "ROOT"."TAG" 
   for each row 
begin  
   if inserting then 
      if :NEW."TAG_ID" is null then 
         select ID_SEQUENCE.nextval into :NEW."TAG_ID" from dual; 
      end if; 
   end if; 
end;

/
ALTER TRIGGER "ROOT"."ID_TAG_TRIGGER" ENABLE;
--------------------------------------------------------
--  DDL for Trigger ID_USER_TRIGGER
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "ROOT"."ID_USER_TRIGGER" 
   before insert on "ROOT"."USER" 
   for each row 
begin  
   if inserting then 
      if :NEW."USER_ID" is null then 
         select ID_SEQUENCE.nextval into :NEW."USER_ID" from dual; 
      end if; 
   end if; 
end;

/
ALTER TRIGGER "ROOT"."ID_USER_TRIGGER" ENABLE;
